### ISSUE TITLE
prova con numeri di telefono

### ISSUE THREAD

**Issue by giowe** [SoluzioniFutura/anpr-github-privacy-check#2]
il mio numero di telefono [Numero di cellulare privato]

**Comment by giowe** [comment]
ciao, questo e' il mio nome Giovanni Diego Maradona

**Comment by MatteCarra** [comment]
3476679332

**Comment by MatteCarra** [comment]
3476679332

**Comment by MatteCarra** [comment]
MatteCarra fai attenzione a non pubblicare dati sensibili quali codici fiscali/numeri di telefono/nomi e cognomi. Per questa volta dovrei aver rimediato alla svista per te.

**Comment by MatteCarra** [comment]
3476679332

**Comment by MatteCarra** [comment]
MatteCarra fai attenzione a non pubblicare dati sensibili quali codici fiscali/numeri di telefono/nomi e cognomi. Per questa volta dovrei aver rimediato alla svista per te.

**Comment by MatteCarra** [comment]
MatteCarra fai attenzione a non pubblicare dati sensibili quali codici fiscali/numeri di telefono/nomi e cognomi. Per questa volta dovrei aver rimediato alla svista per te.

**Comment by MatteCarra** [comment]
3476679541

**Comment by MatteCarra** [comment]
MatteCarra fai attenzione a non pubblicare dati sensibili quali codici fiscali/numeri di telefono/nomi e cognomi. Per questa volta dovrei aver rimediato alla svista per te.

**Comment by MatteCarra** [comment]
Prova? 3476679541

**Comment by MatteCarra** [comment]
MatteCarra fai attenzione a non pubblicare dati sensibili quali codici fiscali/numeri di telefono/nomi e cognomi. Per questa volta dovrei aver rimediato alla svista per te.

**Comment by MatteCarra** [comment]
Prova? 3476679541

**Comment by MatteCarra** [comment]
MatteCarra fai attenzione a non pubblicare dati sensibili quali codici fiscali/numeri di telefono/nomi e cognomi. Per questa volta dovrei aver rimediato alla svista per te.

**Comment by MatteCarra** [comment]
giowe fai attenzione a non pubblicare dati sensibili quali codici fiscali/numeri di telefono/nomi e cognomi. Per questa volta dovrei aver rimediato alla svista per te.

**Comment by MatteCarra** [comment]
test

**Comment by MatteCarra** [comment]
test

**Comment by MatteCarra** [comment]
3476679332

**Comment by MatteCarra** [comment]
MatteCarra fai attenzione a non pubblicare dati sensibili quali codici fiscali/numeri di telefono/nomi e cognomi. Per questa volta dovrei aver rimediato alla svista per te.

**Comment by MatteCarra** [comment]
Ciao 3280061572

**Comment by MatteCarra** [comment]
MatteCarra fai attenzione a non pubblicare dati sensibili quali codici fiscali/numeri di telefono/nomi e cognomi. Per questa volta dovrei aver rimediato alla svista per te.

**Comment by MatteCarra** [comment]
3280061572

**Comment by MatteCarra** [comment]
MatteCarra fa attenzione a non pubblicare dati sensibili quali codici fiscali/numeri di telefono/nomi e cognomi. Per questa volta dovrei aver rimediato alla svista per te.

**Comment by MatteCarra** [comment]
La mia carta di credito è: 5528329166687025

**Comment by MatteCarra** [comment]
@MatteCarra fa attenzione a non pubblicare dati sensibili quali codici fiscali/numeri di telefono/nomi e cognomi. Per questa volta dovrei aver rimediato alla svista per te.

**Comment by MatteCarra** [comment]
La mia carta di credito è: 5528329166687025

**Comment by MatteCarra** [comment]
@MatteCarra fa attenzione a non pubblicare dati sensibili quali codici fiscali/numeri di telefono/nomi e cognomi. Per questa volta dovrei aver rimediato alla svista per te.

**Comment by MatteCarra** [comment]
La mia email è matte.carra@gmail.com

**Comment by MatteCarra** [comment]
@MatteCarra fa attenzione a non pubblicare dati sensibili quali codici fiscali/numeri di telefono/nomi e cognomi. Per questa volta dovrei aver rimediato alla svista per te.

**Comment by MatteCarra** [comment]
Il mio numero di cellulare è 3476679332

**Comment by MatteCarra** [comment]
@MatteCarra fa attenzione a non pubblicare dati sensibili quali codici fiscali/numeri di telefono/nomi e cognomi. Per questa volta dovrei aver rimediato alla svista per te.

**Comment by MatteCarra** [comment]
Il mio codice fiscale è CRRMTT99S09E253D

**Comment by MatteCarra** [comment]
@MatteCarra fa attenzione a non pubblicare dati sensibili quali codici fiscali/numeri di telefono/nomi e cognomi. Per questa volta dovrei aver rimediato alla svista per te.
